/// Hive Types
const int HIVE_TYPE_ID_BOOK_VO = 1;
const int HIVE_TYPE_ID_BUY_LINK_VO = 2;
const int HIVE_TYPE_ID_GET_OVERVIEW_RESULT_VO = 3;
const int HIVE_TYPE_ID_HORIZONTAL_BOOK_LIST_ITEM_VO = 4;
const int HIVE_TYPE_ID_MORE_BOOK_LIST_ITEM_VO = 5;
const int HIVE_TYPE_ID_ISBN_VO = 6;
const int HIVE_TYPE_ID_REVIEW_VO = 7;
const int HIVE_TYPE_ID_BOOK_LIST_FOR_HIVE_VO = 8;
const int HIVE_TYPE_ID_SHELF_VO = 9;

/// Box Names
const String BOX_NAME_BOOK_VO = "BOX_NAME_BOOK_VO";
const String BOX_NAME_BOOK_VO_FOR_CAROUSEL = "BOX_NAME_BOOK_VO_FOR_CAROUSEL";
const String BOX_NAME_BOOK_VO_FOR_SEARCH_RESULT = "BOX_NAME_BOOK_VO_FOR_SEARCH_RESULT";
const String BOX_NAME_SHELF_VO = "BOX_NAME_SHELF_VO";